# Generated by Django 4.2.7 on 2025-12-10 21:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(help_text='Telegram chat ID for this user', max_length=255, unique=True)),
                ('critical_alerts_enabled', models.BooleanField(default=True)),
                ('daily_digest_enabled', models.BooleanField(default=True)),
                ('weekly_report_enabled', models.BooleanField(default=True)),
                ('digest_time', models.TimeField(default=datetime.time(8, 0), help_text='Time to send daily digest')),
                ('custom_threshold_days', models.IntegerField(blank=True, help_text='Custom alert threshold, overrides company default', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'indexes': [models.Index(fields=['chat_id'], name='accounts_te_chat_id_099667_idx'), models.Index(fields=['user', 'is_active'], name='accounts_te_user_id_104be7_idx')],
            },
        ),
    ]
