# Generated by Django 6.0 on 2025-12-07 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("po_number", models.CharField(max_length=100, unique=True)),
                ("order_date", models.DateField(db_index=True)),
                (
                    "expected_delivery",
                    models.DateField(
                        blank=True, help_text="Expected delivery date", null=True
                    ),
                ),
                (
                    "actual_delivery",
                    models.DateField(
                        blank=True, help_text="Actual delivery date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=255)),
                ("supplier_data", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_ordered", models.IntegerField()),
                ("quantity_received", models.IntegerField(default=0)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_items",
                        to="products.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["purchase_order", "product"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("analysis_date", models.DateField(db_index=True)),
                ("current_stock", models.IntegerField()),
                (
                    "daily_burn_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Average daily sales", max_digits=10
                    ),
                ),
                (
                    "runway_days",
                    models.IntegerField(
                        help_text="Days until stockout at current burn rate"
                    ),
                ),
                (
                    "stockout_date",
                    models.DateField(
                        blank=True, help_text="Predicted date of stockout", null=True
                    ),
                ),
                (
                    "recommended_quantity",
                    models.IntegerField(
                        default=0, help_text="Suggested order quantity"
                    ),
                ),
                (
                    "action_category",
                    models.CharField(
                        choices=[
                            ("ORDER_TODAY", "Order Today"),
                            ("ALREADY_ORDERED", "Already Ordered"),
                            ("ATTENTION_REQUIRED", "Attention Required"),
                            ("NORMAL", "Normal - No Action Needed"),
                        ],
                        default="NORMAL",
                        max_length=50,
                    ),
                ),
                (
                    "priority_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Urgency score (0-100)",
                        max_digits=5,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_recommendations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority_score", "runway_days"],
                "indexes": [
                    models.Index(
                        fields=["product", "analysis_date"],
                        name="procurement_product_5495ee_idx",
                    ),
                    models.Index(
                        fields=["action_category", "analysis_date"],
                        name="procurement_action__4c1de2_idx",
                    ),
                    models.Index(
                        fields=["-priority_score"],
                        name="procurement_priorit_c778df_idx",
                    ),
                ],
                "unique_together": {("product", "analysis_date")},
            },
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["company", "order_date"], name="procurement_company_17adc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["status"], name="procurement_status_6b6895_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorderitem",
            unique_together={("purchase_order", "product")},
        ),
    ]
