# Generated by Django 6.0 on 2025-12-07 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySalesAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_quantity", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("wildberries_quantity", models.IntegerField(default=0)),
                (
                    "wildberries_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("ozon_quantity", models.IntegerField(default=0)),
                (
                    "ozon_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_sales",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["product", "date"],
                        name="sales_daily_product_0fdbc5_idx",
                    ),
                    models.Index(fields=["date"], name="sales_daily_date_f3de61_idx"),
                ],
                "unique_together": {("product", "date")},
            },
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                ("quantity_available", models.IntegerField(default=0)),
                ("quantity_reserved", models.IntegerField(default=0)),
                ("warehouse_id", models.CharField(blank=True, max_length=100)),
                ("warehouse_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_snapshots",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["product", "snapshot_date"],
                        name="sales_inven_product_06ffca_idx",
                    )
                ],
                "unique_together": {("product", "snapshot_date", "warehouse_id")},
            },
        ),
        migrations.CreateModel(
            name="SalesHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("quantity", models.IntegerField()),
                ("day_of_week", models.IntegerField()),
                ("is_weekend", models.BooleanField(default=False)),
                ("is_holiday", models.BooleanField(default=False)),
                ("is_promo", models.BooleanField(default=False)),
                ("promo_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_history",
                        to="accounts.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_history",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["product", "date"],
                        name="sales_sales_product_971bab_idx",
                    ),
                    models.Index(
                        fields=["company", "date"],
                        name="sales_sales_company_709a85_idx",
                    ),
                ],
                "unique_together": {("product", "date")},
            },
        ),
        migrations.CreateModel(
            name="SalesTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[("WILDBERRIES", "Wildberries"), ("OZON", "Ozon")],
                        max_length=50,
                    ),
                ),
                ("sale_date", models.DateField(db_index=True)),
                ("quantity", models.IntegerField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_reference", models.CharField(blank=True, max_length=200)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_transactions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date", "-synced_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "sale_date"],
                        name="sales_sales_product_c2adde_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "sale_date"],
                        name="sales_sales_marketp_a7ed9d_idx",
                    ),
                    models.Index(
                        fields=["product", "marketplace", "sale_date"],
                        name="sales_sales_product_325d45_idx",
                    ),
                ],
            },
        ),
    ]
