# Generated by Django 4.2.7 on 2025-12-10 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_marketplaceproduct_marketplace'),
        ('accounts', '0002_telegramsubscription'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Inbound - Stock Increase'), ('OUTBOUND', 'Outbound - Sales/Consumption'), ('TRANSFER', 'Transfer Between Warehouses'), ('ADJUSTMENT', 'Manual Adjustment'), ('SYNC_UPDATE', 'Marketplace Synchronization'), ('INITIAL_LOAD', 'Initial Inventory Load')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for inbound, negative for outbound')),
                ('movement_date', models.DateTimeField(db_index=True)),
                ('reference_type', models.CharField(blank=True, choices=[('SALE', 'Sales Transaction'), ('PURCHASE_ORDER', 'Purchase Order'), ('ADJUSTMENT', 'Manual Adjustment'), ('SYNC', 'API Synchronization'), ('IMPORT', 'Bulk Import')], max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='ID of related record (sale, PO, etc.)', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('warehouse_type', models.CharField(choices=[('OWN', 'Own Warehouse'), ('MARKETPLACE_FF', 'Marketplace Fulfillment')], default='OWN', max_length=20)),
                ('marketplace', models.CharField(blank=True, choices=[('WILDBERRIES', 'Wildberries'), ('OZON', 'Ozon'), ('WEBSITE', 'Website')], help_text='Associated marketplace for MARKETPLACE_FF type', max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Designates the default warehouse')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company', '-is_primary', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='inventorysnapshot',
            old_name='warehouse_id',
            new_name='legacy_warehouse_id',
        ),
        migrations.AlterUniqueTogether(
            name='inventorysnapshot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='marketplace',
            field=models.CharField(choices=[('WILDBERRIES', 'Wildberries'), ('OZON', 'Ozon'), ('WEBSITE', 'Website/E-commerce')], max_length=50),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='sales.warehouse'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'warehouse_type'], name='sales_wareh_company_cff896_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'is_primary'], name='sales_wareh_company_91fe95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'movement_date'], name='sales_inven_product_8a922b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['warehouse', 'movement_date'], name='sales_inven_warehou_3d1408_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'warehouse', 'movement_date'], name='sales_inven_product_c370dc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='sales_inven_referen_9da4f9_idx'),
        ),
    ]