# Generated by Django 4.2.7 on 2025-12-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_warehouse_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysnapshot',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse location for this inventory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='sales.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['product', 'warehouse', 'snapshot_date'], name='sales_inven_product_8a7182_idx'),
        ),
    ]