# Generated by Django 4.2.7 on 2025-12-21 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_marketplaceproduct_marketplace"),
        ("sales", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventorysnapshot",
            unique_together={("product", "warehouse", "snapshot_date")},
        ),
    ]
