# Generated by Django 6.0 on 2025-12-07 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=500)),
                ("category", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "sku"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[("WILDBERRIES", "Wildberries"), ("OZON", "Ozon")],
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(max_length=200)),
                ("barcode", models.CharField(blank=True, max_length=200)),
                ("external_data", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_mappings",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "marketplace"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=200)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Weight in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Length in cm",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Width in cm",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in cm",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reorder_threshold_days",
                    models.IntegerField(
                        default=7,
                        help_text="Days of inventory runway that triggers reorder",
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(
                        default=14, help_text="Days from order to delivery"
                    ),
                ),
                (
                    "safety_stock_days",
                    models.IntegerField(
                        default=3, help_text="Buffer days beyond lead time"
                    ),
                ),
                (
                    "minimum_order_quantity",
                    models.IntegerField(
                        default=1, help_text="Minimum viable order size"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extended_attributes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Attributes",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "sku"], name="products_pr_company_e57b48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "is_active"], name="products_pr_company_088709_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "category"], name="products_pr_company_1a1f01_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("company", "sku")},
        ),
        migrations.AddIndex(
            model_name="marketplaceproduct",
            index=models.Index(
                fields=["marketplace", "external_id"],
                name="products_ma_marketp_84ab2a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceproduct",
            index=models.Index(
                fields=["product", "active"], name="products_ma_product_c9c467_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketplaceproduct",
            unique_together={("product", "marketplace")},
        ),
    ]
