# Generated by Django 4.2.7 on 2025-12-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceproduct',
            name='marketplace',
            field=models.CharField(choices=[('WILDBERRIES', 'Wildberries'), ('OZON', 'Ozon'), ('WEBSITE', 'Website/E-commerce')], max_length=50),
        ),
    ]
