# Generated by Django 6.0 on 2025-12-07 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("forecast_date", models.DateField(db_index=True)),
                ("predicted_quantity", models.IntegerField()),
                (
                    "confidence_lower",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Lower bound of prediction interval",
                        max_digits=10,
                    ),
                ),
                (
                    "confidence_upper",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Upper bound of prediction interval",
                        max_digits=10,
                    ),
                ),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Model confidence percentage",
                        max_digits=5,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["forecast_date"],
                "indexes": [
                    models.Index(
                        fields=["product", "forecast_date"],
                        name="forecasting_product_d8651b_idx",
                    ),
                    models.Index(
                        fields=["generated_at"], name="forecasting_generat_53dbba_idx"
                    ),
                ],
                "unique_together": {("product", "forecast_date")},
            },
        ),
        migrations.CreateModel(
            name="ForecastAccuracy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("evaluation_date", models.DateField(db_index=True)),
                ("forecast_date", models.DateField()),
                ("predicted_value", models.IntegerField()),
                ("actual_value", models.IntegerField()),
                ("absolute_error", models.IntegerField()),
                (
                    "percentage_error",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("model_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_accuracy",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-evaluation_date"],
                "indexes": [
                    models.Index(
                        fields=["product", "evaluation_date"],
                        name="forecasting_product_e031ce_idx",
                    )
                ],
            },
        ),
    ]
